### ISSUE TITLE
[Question] TEI vs TGI for embedding models

### ISSUE THREAD

**Issue by austinmw** [andrewrreed/hf-notebooks#1]
Hi, just want to double check: is the main advantage of using TEI to deploy models like BGE that you don't need to include custom inference code? Or are there other advantages/optimizations? 

(compared to using TGI with `HuggingFaceModel(env={"HF_TASK": "feature-extraction"},...)`)

**Comment by andrewrreed** [comment]
There are a bunch of advantages over just the regular HF DLC that makes it super fast - main ones being:
- written in Rust
- supports dynamic batching
- Optimized implementations (e.g. flash attention)

**Comment by austinmw** [comment]
@andrewrreed  Oh I meant compared to the HF TGI container, not the standard HF container

**Comment by andrewrreed** [comment]
Hmmm you can't use TGI for embeddings, it only supports text generation (i.e. decoder-based) models

**Comment by austinmw** [comment]
Ah, thanks, nvm, I guess I was deploying to `763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:2.0-transformers4.28-gpu-py310-cu118-ubuntu20.04`
